name: Node.js Build, Test, Deploy

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarn
        run: yarn install --pure-lockfile

      - name: Run Tests
        run: yarn test
        env:
          PORT: 5000
          AWS_DEFAULT_REGION: us-east-1
          JWT_SECRET: dummy_secret_goes_here
          JWT_EXPIRATION_TIME: 1h
          JWT_REFRESH_EXPIRATION_TIME: 5h
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: test-key
          AWS_SECRET_ACCESS_KEY: test-secret-key

      - name: Export Coverage Report
        run: |
          sed -i 's+/home/runner/work/jv-backend/jv-backend+/github/workspace+g' coverage/lcov.info

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Docker Build and Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.0.0
        with:
          heroku_api_key: ${{secrets.HEROKU_TOKEN}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_PROD}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
